### ISSUE TITLE
The ip checker is not stable.

### ISSUE THREAD

**Issue by MewX** [anhldbk/privoxyTor#2]
![image](https://user-images.githubusercontent.com/5752560/33592959-31fccc1e-d9dd-11e7-80fb-de32b854e5e2.png)

It has a large probability to be hijacked by Cloudflare firewall.

**Comment by anhldbk** [comment]
@MewX Would you explain your issue more?

**Comment by MewX** [comment]
Oh, I'm really sorry, it was the error from another repo!
Thanks for your time!
